### ISSUE TITLE
Nombre de función poco clara

### ISSUE THREAD

**Issue by julianbega** [Eliaxter/Arkanoid#1]
Feedback no es clara, quizá how to play sería mas intuitivo
cuando lo leo tengo que leer todo lo que hace cada funcion para entender que es feedback
DrawWindowFeedBack solo hace ClearBackground

**Comment by eliasbrucart** [comment]
Eliminada la función DrawWindowFeedBack y cambiado el nombre de la funcion Feedback a HowToPlay, el estado cambio de Feedback a Instructions
