### ISSUE TITLE
Error de tipo de dato en ball

### ISSUE THREAD

**Issue by julianbega** [Eliaxter/Arkanoid#4]
if (previusFrameCollisionBall)
		{
			lastCollisionFramesBall++;
			if (lastCollisionFramesBall >= dontCheckCollisionFrames)
			{
				previusFrameCollision = 0;
				lastCollisionFramesBall = false;
			}
		}
se usa lastCollisionFramesBall como int y como bool
se compara a un bool con un const int que es de 20 por lo que todo el if es un sin sentido

**Comment by julianbega** [comment]
Pasa exactamente lo mismo en player

**Comment by eliasbrucart** [comment]
Se ha corregido el tipo de dato de lastCollisionFramesBall
